<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f6ef3e4f-1bc0-4449-a2d3-a8a7d6b8cd93</testSuiteGuid>
   <testCaseLink>
      <guid>5707d911-35cf-4b68-80bf-36cb0823a2eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login as Coach</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2164cd84-f95f-40ca-801c-d84197df23a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a1c4c2d-a33d-4cd1-8b56-560d054bc9a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8088277-e000-4747-bd8f-d01fd4374d91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login as Coach_blank email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f604ae76-0bf5-46f3-8c46-323f734246a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df645281-249d-4b81-a46a-03969af2e804</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a47b1167-b2ac-4881-9a91-abf546b27f94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login as Coach_blank password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2057a95-6e55-4c23-b566-29002ab82e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4fa0d3d-9506-40a7-bcec-137f33bcdb4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>350a1a66-c870-4b12-8b99-238adbce9101</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login as Coach_incorrect password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>972bf6cf-362f-4bee-9a75-d55311d41b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ddaa00-a8ac-4025-8ab0-99570938e434</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
